# Generated by Django 5.2.7 on 2025-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dia_evento',
            field=models.CharField(max_length=100, verbose_name='Dia do evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='end_evento',
            field=models.CharField(max_length=255, verbose_name='Local do evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_club',
            field=models.CharField(max_length=200, verbose_name='Nome do Club'),
        ),
    ]
