# Generated by Django 5.2.7 on 2025-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0002_alter_evento_dia_evento_alter_evento_end_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_ingresso',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
