# Generated by Django 5.2.5 on 2025-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0003_evento_link_ingresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presskit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Presskit Oficial', max_length=100)),
                ('arquivo', models.FileField(upload_to='presskit/', verbose_name='Arquivo do Presskit')),
                ('data_upload', models.DateTimeField(auto_now=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Presskit',
                'verbose_name_plural': 'Presskits',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.AlterField(
            model_name='evento',
            name='link_ingresso',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='link do ingreço'),
        ),
    ]
