# Generated by Django 5.2.8 on 2025-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0004_presskit_alter_evento_link_ingresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título da Foto')),
                ('foto', models.ImageField(upload_to='galeria/', verbose_name='Arquivo de Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['-data_upload'],
            },
        ),
    ]
