# Generated by Django 5.2.8 on 2025-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0005_fotogaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo para identificar (opicional) ', max_length=100)),
                ('imagem', models.ImageField(upload_to='carrossel/', verbose_name='Imagem do Slide')),
                ('ativo', models.BooleanField(default=True, help_text='se for marcado, a imagem aparerá no site')),
                ('ordem', models.IntegerField(default=0, help_text='Menor número aparece primeiro')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do carrossel',
                'ordering': ['ordem'],
            },
        ),
    ]
