# Generated by Django 5.2.8 on 2026-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0006_imagemcarrossel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Vídeo de Fundo', max_length=100)),
                ('arquivo_video', models.FileField(upload_to='videos/', verbose_name='Arquivo de Vídeo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vídeo de Destaque',
                'verbose_name_plural': 'Vídeos de Destaque',
            },
        ),
        migrations.AlterModelOptions(
            name='presskit',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Download Logo', 'verbose_name_plural': 'Downloads Logos'},
        ),
        migrations.AlterField(
            model_name='presskit',
            name='arquivo',
            field=models.FileField(upload_to='logos/', verbose_name='Arquivo com Logos'),
        ),
        migrations.AlterField(
            model_name='presskit',
            name='titulo',
            field=models.CharField(default='Logo Oficial', max_length=100),
        ),
    ]
