# Generated by Django 5.2.8 on 2026-03-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDJDEXX', '0007_videodestaque_alter_presskit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link_ingresso',
        ),
        migrations.AddField(
            model_name='evento',
            name='link_flayer',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='link do flayer'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(default='Nome Testes', max_length=200, verbose_name='Nome do evento'),
            preserve_default=False,
        ),
    ]
